name: Test & Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  NODE_ENV: ${{ inputs.environment }}

jobs:
  test:
    steps:
      - run: npm ci
      - run: npm run build
