name: Test & Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  NODE_ENV: ${{ inputs.environment }}

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
